export function configure (config) {
  config.globalResources([
    './icon',
    './user-panel',
    './create-issue',
    './assign-users',
    './comments-list',
    './comment',
    './viewing-text-editor',
    './status-drop-down',
    './select-dropdown',
    './issue-type',
    './autocomplete',
    './sub-task-list',
    './user-display',
    './changelog-display',
    './issue-description',
    './notification-host'
  ])
}
